git:
  paging:
    externalDiffCommand: difft --display=inline --tab-width=2 --syntax-highlight=off

os:
  edit: "nvr --remote {{filename}}"
  editAtLine: "nvr --remote +{{line}} {{filename}}"
  editAtLineAndWait: "nvr --remote-wait +{{line}} {{filename}}"
  editInTerminal: false

gui:
  theme:
    selectedLineBgColor:
      - "#5B595C"
    activeBorderColor:
      - yellow
      - bold
    inactiveBorderColor:
      - "#939293"
